SET HDRV=C:
SET HDIR=\PROJECTS\JDS

SET PATH=C:\TOOLKT20\OS2BIN;C:\IBMWF\BIN;C:\IBMC\BIN;%PATH%

rem IBM IPFC Environment follows:
SET IPFC=C:\TOOLKT20\IPFC;


SET HELP=C:\TOOLKT20\OS2HELP;C:\IBMWF\HELP;%HELP%
SET BOOKSHELF=C:\IBMWF\HELP;C:\TOOLKT20\OS2HELP;%BOOKSHELF%
SET HELPNDX=EPMKWHLP.NDX
SET DPATH=C:\IBMC\LOCALE;C:\IBMC\HELP;%DPATH%




MD  C:\TOOLKT20\SC\TMP >NUL
SET TMP=C:\TOOLKT20\SC\TMP
MD  C:\IBMC\TMP  >NUL
SET TMP=C:\IBMC\TMP

SET TZ=EST5EDT,0,0,0,0,0,0,0,0,0


rem IBM SOM Compiler Environment follows:
rem IBM C/2 Compiler Environment follows:
SET LIB=C:\TOOLKT20\OS2LIB;C:\IBMC\LIB;
SET INCLUDE=C:\TOOLKT20\C\OS2H;C:\IBMC\INCLUDE;C:\TOOLKT20\SC;C:\TOOLKT20\MASM\OS2INC;C:\TOOLKT20\ASM\OS2INC;

