// RESOURCE.H - Constants for resources

#define ID_RESOURCE             1

#define IDM_MAP                 1
#define IDM_MAP_LOAD            2
#define IDM_MAP_SAVE            3
#define IDM_MAP_EDIT            4
#define IDM_ABOUT               5
                      
#define IDM_TERRAIN             10
#define IDM_TER_CLEAR_GROUND    11
#define IDM_TER_ROUGH_GROUND    12
#define IDM_TER_WATER           13
#define IDM_TER_LIGHT_WOODS     14
#define IDM_TER_HEAVY_WOODS     15
#define IDM_TER_PAVEMENT        16
#define IDM_TER_BRIDGE          17
#define IDM_TER_LIGHT_BLDG      18
#define IDM_TER_MEDIUM_BLDG     19
#define IDM_TER_HEAVY_BLDG      20
#define IDM_TER_HARD_BLDG       21
