#define ID_RESOURCE             1

#define IDM_MAP                 10
#define IDM_MAP_LOAD            11
#define IDM_MAP_SAVE            12
#define IDM_MAP_EDIT            13
#define IDM_ABOUT               14
                      
#define IDM_TERRAIN             20
#define IDM_TER_CLEAR_GROUND    21
#define IDM_TER_ROUGH_GROUND    22
#define IDM_TER_WATER           23
#define IDM_TER_LIGHT_WOODS     24
#define IDM_TER_HEAVY_WOODS     25
#define IDM_TER_PAVEMENT        26
#define IDM_TER_BRIDGE          27
#define IDM_TER_LIGHT_BLDG      28
#define IDM_TER_MEDIUM_BLDG     29
#define IDM_TER_HEAVY_BLDG      30
#define IDM_TER_HARD_BLDG       31
