/* dialog boxes for OS/2 Programmer's Editor */

#include <os2.h>

MRESULT EXPENTRY AboutDlgProc (HWND, USHORT, MPARAM, MPARAM);
MRESULT EXPENTRY OpenDlgProc   (HWND, USHORT, MPARAM, MPARAM);
MRESULT EXPENTRY SaveasDlgProc (HWND, USHORT, MPARAM, MPARAM);
MRESULT EXPENTRY FindDlgProc (HWND, USHORT, MPARAM, MPARAM);
MRESULT EXPENTRY ReplaceDlgProc (HWND, USHORT, MPARAM, MPARAM);
MRESULT EXPENTRY GoLnDlgProc (HWND, USHORT, MPARAM, MPARAM);
SHORT ParseFileName (CHAR*, CHAR*);
