#define ID_RESOURCE             1

#define IDM_FILE                100
#define IDM_FILE_LOAD           101
#define IDM_FILE_SAVE           102
#define IDM_FILE_SAVE_AS        103
#define IDM_ABOUT               105

#define IDM_MODE                200
#define IDM_MODE_TARGET         201
#define IDM_MODE_EDIT           202
                      
#define IDM_TERRAIN             300
#define IDM_TER_CLEAR_GROUND    301
#define IDM_TER_ROUGH_GROUND    302
#define IDM_TER_WATER           303
#define IDM_TER_LIGHT_WOODS     304
#define IDM_TER_HEAVY_WOODS     305
#define IDM_TER_PAVEMENT        306
#define IDM_TER_BRIDGE          307
#define IDM_TER_LIGHT_BLDG      308
#define IDM_TER_MEDIUM_BLDG     309
#define IDM_TER_HEAVY_BLDG      310
#define IDM_TER_HARD_BLDG       311
